# Generated by Django 5.2.7 on 2025-10-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "Descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "Ativo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": "Dashboard",
                "ordering": ["Nome"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard_Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ordem", models.IntegerField(verbose_name="Ordem de Exibição")),
                ("Duracao", models.IntegerField(verbose_name="Duração (segundos)")),
                (
                    "Dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Configuração",
                "verbose_name_plural": "Dashboard Configurações",
                "db_table": "Dashboard_Config",
                "ordering": ["Ordem"],
            },
        ),
    ]
