# Generated by Django 5.2.7 on 2025-10-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendaAtualizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Data", models.CharField(max_length=255, verbose_name="Data")),
                ("Hora", models.CharField(max_length=255, verbose_name="Hora")),
                ("Periodo", models.CharField(max_length=255, verbose_name="Período")),
                (
                    "Inseridos",
                    models.CharField(max_length=255, verbose_name="Inseridos"),
                ),
                (
                    "Atualizados",
                    models.CharField(max_length=255, verbose_name="Atualizados"),
                ),
            ],
            options={
                "verbose_name": "Venda Atualização",
                "verbose_name_plural": "Vendas Atualizações",
                "db_table": "VendaAtualizacao",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendaConfiguracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("Valor", models.CharField(max_length=255, verbose_name="Valor")),
            ],
            options={
                "verbose_name": "Venda Configuração",
                "verbose_name_plural": "Vendas Configurações",
                "db_table": "VendaConfiguracao",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dashboard_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DataHora_Inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora Início"
                    ),
                ),
                (
                    "DataHora_Fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Fim"
                    ),
                ),
                (
                    "Duracao_Exibida",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração Exibida (segundos)"
                    ),
                ),
                (
                    "Tipo_Transicao",
                    models.CharField(
                        choices=[
                            ("automatica", "Automática"),
                            ("manual", "Manual"),
                            ("pausa", "Pausado"),
                        ],
                        default="automatica",
                        max_length=20,
                        verbose_name="Tipo de Transição",
                    ),
                ),
                (
                    "Dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Log",
                "verbose_name_plural": "Dashboard Logs",
                "db_table": "Dashboard_Log",
                "ordering": ["-DataHora_Inicio"],
            },
        ),
    ]
