# Generated by Django 5.2.7 on 2026-01-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_vendaatualizacao_vendaconfiguracao_dashboard_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_gestao",
                    models.CharField(
                        blank=True, db_column="ID_Gestao", max_length=100, null=True
                    ),
                ),
                (
                    "id_loja",
                    models.CharField(
                        blank=True, db_column="ID_Loja", max_length=10, null=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=200, null=True
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, db_column="Descricao", max_length=200, null=True
                    ),
                ),
                (
                    "codigointerno",
                    models.CharField(
                        blank=True, db_column="CodigoInterno", max_length=100, null=True
                    ),
                ),
                (
                    "codigobarra",
                    models.CharField(
                        blank=True, db_column="CodigoBarra", max_length=100, null=True
                    ),
                ),
                (
                    "valorvenda",
                    models.CharField(
                        blank=True, db_column="ValorVenda", max_length=10, null=True
                    ),
                ),
                (
                    "valorcusto",
                    models.CharField(
                        blank=True, db_column="ValorCusto", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "Produtos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "Descricao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "RPA",
                "verbose_name_plural": "RPAs",
                "db_table": "RPA",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendaProdutos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("venda_id", models.CharField(db_column="Venda_ID", max_length=100)),
                ("nome", models.TextField(db_column="Nome")),
                (
                    "detalhes",
                    models.TextField(blank=True, db_column="Detalhes", null=True),
                ),
                (
                    "quantidade",
                    models.CharField(db_column="Quantidade", max_length=100),
                ),
                (
                    "valorcusto",
                    models.CharField(db_column="ValorCusto", max_length=100),
                ),
                (
                    "valorvenda",
                    models.CharField(db_column="ValorVenda", max_length=100),
                ),
                (
                    "valordesconto",
                    models.CharField(db_column="ValorDesconto", max_length=100),
                ),
                (
                    "valortotal",
                    models.CharField(db_column="ValorTotal", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Venda Produto",
                "verbose_name_plural": "Venda Produtos",
                "db_table": "VendaProdutos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vendas",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_gestao", models.CharField(db_column="ID_Gestao", max_length=100)),
                ("codigo", models.CharField(db_column="Codigo", max_length=100)),
                (
                    "clientenome",
                    models.CharField(db_column="ClienteNome", max_length=100),
                ),
                (
                    "vendedornome",
                    models.CharField(db_column="VendedorNome", max_length=100),
                ),
                ("data", models.CharField(db_column="Data", max_length=100)),
                (
                    "situacaonome",
                    models.CharField(db_column="SituacaoNome", max_length=100),
                ),
                (
                    "nomecanalvenda",
                    models.CharField(db_column="NomeCanalVenda", max_length=100),
                ),
                (
                    "condicaopagamento",
                    models.CharField(db_column="CondicaoPagamento", max_length=100),
                ),
                (
                    "valorcusto",
                    models.CharField(db_column="ValorCusto", max_length=100),
                ),
                (
                    "valorprodutos",
                    models.CharField(db_column="ValorProdutos", max_length=100),
                ),
                (
                    "valordesconto",
                    models.CharField(db_column="ValorDesconto", max_length=100),
                ),
                (
                    "valortotal",
                    models.CharField(db_column="ValorTotal", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": "Vendas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VendasSituacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacaonome",
                    models.CharField(
                        blank=True, db_column="SituacaoNome", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda Situação",
                "verbose_name_plural": "Vendas Situações",
                "db_table": "VendasSituacao",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vendedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=100)),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
                "db_table": "Vendedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RPA_Atualizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Data", models.CharField(max_length=100, verbose_name="Data")),
                ("Hora", models.CharField(max_length=100, verbose_name="Hora")),
                (
                    "Periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Período"
                    ),
                ),
                (
                    "Inseridos",
                    models.CharField(max_length=100, verbose_name="Inseridos"),
                ),
                (
                    "Atualizados",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Atualizados",
                    ),
                ),
                (
                    "RPA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.rpa",
                        verbose_name="RPA",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPA Atualização",
                "verbose_name_plural": "RPA Atualizações",
                "db_table": "RPA_Atualizacao",
                "ordering": ["Data"],
            },
        ),
        migrations.DeleteModel(
            name="VendaAtualizacao",
        ),
        migrations.AddField(
            model_name="dashboard_config",
            name="Mensagem",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mensagem"
            ),
        ),
    ]
