# Generated by Django 5.2.7 on 2026-05-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_produtos_rpa_vendaprodutos_vendas_vendassituacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={
                "managed": False,
                "ordering": ["Nome"],
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
            },
        ),
        migrations.AlterModelOptions(
            name="dashboard_config",
            options={
                "managed": False,
                "ordering": ["Ordem"],
                "verbose_name": "Dashboard Configuração",
                "verbose_name_plural": "Dashboard Configurações",
            },
        ),
        migrations.AlterModelOptions(
            name="dashboard_log",
            options={
                "managed": False,
                "ordering": ["-DataHora_Inicio"],
                "verbose_name": "Dashboard Log",
                "verbose_name_plural": "Dashboard Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="rpa_atualizacao",
            options={
                "managed": False,
                "ordering": ["Data"],
                "verbose_name": "RPA Atualização",
                "verbose_name_plural": "RPA Atualizações",
            },
        ),
    ]
